name: Build bottles

on: pull_request

env:
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  BINTRAY_ORG: linuxbrew
  BINTRAY_ROOT_URL: https://linuxbrew.bintray.com/bottles-num

jobs:
  build-linux-bottles:
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    steps:
      - name: Update Homebrew
        run: brew update-reset

      - name: Check out tap
        uses: actions/checkout@main

      - name: Set up tap
        run: |
          tap_dir="$(brew --repo ${{github.repository}})"
          mkdir -p "$(dirname $tap_dir)"
          ln -s "$GITHUB_WORKSPACE" "$tap_dir"

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - name: Run brew test-bot --only-formulae
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --only-formulae --local --bintray-org=$BINTRAY_ORG --root-url=$BINTRAY_ROOT_URL

      - name: Output brew test-bot --only-formulae failures
        if: always()
        run: |
          cat ~/bottles/steps_output.txt
          rm ~/bottles/steps_output.txt

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: logs (Linux)
          path: ~/bottles/logs

      - name: Delete logs and home
        if: always()
        run: |
          rm -rvf ~/bottles/logs
          rm -rvf ~/bottles/home

      - name: Count bottles
        id: bottles
        if: always()
        run: |
          cd ~/bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"

      - name: Upload bottles
        if: always() && steps.bottles.outputs.count > 0
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: ~/bottles

  build-macos-bottles:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew
        run: brew update-reset

      - name: Check out tap
        uses: actions/checkout@main

      - name: Set up tap
        run: |
          tap_dir="$(brew --repo ${{github.repository}})"
          mkdir -p "$(dirname $tap_dir)"
          ln -s "$GITHUB_WORKSPACE" "$tap_dir"

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - name: Run brew test-bot --only-formulae
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --only-formulae --local --bintray-org=$BINTRAY_ORG --root-url=$BINTRAY_ROOT_URL

      - name: Output brew test-bot --only-formulae failures
        if: always()
        run: |
          cat ~/bottles/steps_output.txt
          rm ~/bottles/steps_output.txt

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: logs (macOS)
          path: ~/bottles/logs

      - name: Delete logs and home
        if: always()
        run: |
          rm -rvf ~/bottles/logs
          rm -rvf ~/bottles/home

      - name: Count bottles
        id: bottles
        if: always()
        run: |
          cd ~/bottles
          count=$(ls *.json | wc -l | xargs echo -n)
          echo "$count bottles"
          echo "::set-output name=count::$count"

      - name: Upload bottles
        if: always() && steps.bottles.outputs.count > 0
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: ~/bottles
